export const LOAD_TAPETE_VERMELHOS = 'App/TapeteVermelho/LOAD_TAPETE_VERMELHOS';
export const LOAD_TAPETE_VERMELHOS_SUCCESS = 'App/TapeteVermelho/LOAD_TAPETE_VERMELHOS_SUCCESS';
export const LOAD_TAPETE_VERMELHOS_ERROR = 'App/TapeteVermelho/LOAD_TAPETE_VERMELHOS_ERROR';
